# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Gems
gems: [jekyll-paginate]

google_verify: 2D5zbZ2Vatb8CeFj1cUCRdJZ3SQatSUlQesml02jEPo
# Setup
title:               炒Ｂ真播
tagline:             '和大家分析实时比特币和山寨币行情'
Archive:             '/archive'
Resourse:			 '/resource'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 www.cryptocotta.club
baseurl:             ''
paginate:            10
rss:				 atom.xml

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-66527403-1'

# Make redcarpet behave like GitHub Flavored Markdown 
redcarpet: 
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

contact_PK: 635207fe87a9b8e111b6790052148d41

# About/contact
author:    
  name:              CryptoCotta
  twitter:           CryptoCotta
  email:             2015rpro@gmail.com
  github:			 JizongL
  linkedin: 		 jizongliang
  gravatar_md5:		 0f8154e563aa3319f1ebc77be5fca304
# Custom vars
version:             1.0.0

