# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true


# Setup
title:               TmmGeek
tagline:             'A blog for bioinformatics programming and statistics'
Archive:             '/archive'
Resourse:			 '/resource'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
rss:				 atom.xml

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-66527403-1'

# Make redcarpet behave like GitHub Flavored Markdown 
redcarpet: 
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# About/contact
author:    
  name:              TmmGeek
  twitter:           jizongliang
  email:             davidliangtmm@gmail.com
  github:			 JizongL
  linkedin: 		 jizongliang
  gravatar_md5:		 0f8154e563aa3319f1ebc77be5fca304
# Custom vars
version:             1.0.0

